# Worker Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-storage-pv
  labels:
    storage: "nfs"
spec:
  capacity:
    storage: {{ .Values.nfs.capacity }}
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  hostPath:
    path: /mnt/nfs
  persistentVolumeReclaimPolicy: Recycle