apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-storage-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    storage: "nfs"
spec:
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfs.capacity }}