apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cerebro/nodename
                operator: In
                values:
                - node0
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: pvc-storage-vol
      volumes:
        - name: pvc-storage-vol
          persistentVolumeClaim:
            claimName: nfs-storage-pvc